import type { Option } from "./caseConfig";

export const nationalities: Option[] = [
  { value: "saudi", label: "السعودية" },
  { value: "uae", label: "الإمارات" },
  { value: "kuwait", label: "الكويت" },
  { value: "qatar", label: "قطر" },
  { value: "bahrain", label: "البحرين" },
  { value: "oman", label: "سلطنة عُمان" },
  { value: "yemen", label: "اليمن" },
  { value: "egypt", label: "مصر" },
  { value: "jordan", label: "الأردن" },
  { value: "syria", label: "سوريا" },
  { value: "lebanon", label: "لبنان" },
  { value: "palestine", label: "فلسطين" },
  { value: "iraq", label: "العراق" },
  { value: "morocco", label: "المغرب" },
  { value: "algeria", label: "الجزائر" },
  { value: "tunisia", label: "تونس" },
  { value: "libya", label: "ليبيا" },
  { value: "sudan", label: "السودان" },
  { value: "somalia", label: "الصومال" },
  { value: "djibouti", label: "جيبوتي" },
  { value: "comoros", label: "جزر القمر" },
  { value: "mauritania", label: "موريتانيا" },
  { value: "turkey", label: "تركيا" },
  { value: "iran", label: "إيران" },
  { value: "pakistan", label: "باكستان" },
  { value: "india", label: "الهند" },
  { value: "bangladesh", label: "بنغلاديش" },
  { value: "indonesia", label: "إندونيسيا" },
  { value: "malaysia", label: "ماليزيا" },
  { value: "philippines", label: "الفلبين" },
  { value: "afghanistan", label: "أفغانستان" },
  { value: "uk", label: "المملكة المتحدة" },
  { value: "usa", label: "الولايات المتحدة" },
  { value: "canada", label: "كندا" },
  { value: "australia", label: "أستراليا" },
  { value: "germany", label: "ألمانيا" },
  { value: "france", label: "فرنسا" },
  { value: "italy", label: "إيطاليا" },
  { value: "spain", label: "إسبانيا" },
  { value: "other", label: "أخرى" },
];
